### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by cgivre** [wise-coders/salesforce-jdbc-driver#1]
Thank you very much for releasing this driver as an open source project.  I wasn't clear what license this driver was released under, but I saw in the source code it was released under the BSD.  

Could you please clarify and add a LICENSE file to the repo?  Thanks!!

**Comment by wise-coders** [comment]
Done.

Best regards,
 Dragos Pruteanu

**Comment by cgivre** [comment]
Thanks!
