### ISSUE TITLE
Broken Download Link to Binary

### ISSUE THREAD

**Issue by cgivre** [wise-coders/salesforce-jdbc-driver#2]
Thanks for all your work on this driver.  It looks like the link to download the driver is broken.  Can you provide a direct link to the JAR or binary?

**Comment by wise-coders** [comment]
Please add a screenshot with the page you try to download it from. Just to check the same location.

Best regards,
 Dragos Pruteanu

**Comment by cgivre** [comment]
Do I have to download the whole product, or can I just download the driver?

![Screen Shot 2021-07-22 at 1 53 45 PM](https://user-images.githubusercontent.com/5513150/126693284-4b4b7200-3315-4312-8cb8-92ffb25be8db.png)

![Screen Shot 2021-07-22 at 1 53 56 PM](https://user-images.githubusercontent.com/5513150/126693274-56aea63f-03e9-430d-8142-1beae4584398.png)

**Comment by wise-coders** [comment]
We have found the broken link and fixed it.
You don't need to download the complete product. But it can be useful to download it in order to test the driver and the connectivity with the database. For 2 weeks it works for free.
