### ISSUE TITLE
Can't pull the Entity and Field Descriptions 

### ISSUE THREAD

**Issue by paulpest** [wise-coders/salesforce-jdbc-driver#7]
Oddly, it appears you must use the tooling api to get the descriptions from the EntityDefinition and FieldDefinition tables.

Please implement access to this information within your driver. 

I can provide the queries I used. I had to write some Python code to pull this information using the salesforce-api package. It had just enough support to make it possible.

**Comment by wise-coders** [comment]
Yes, we can implement it. Any suggestion about how to access this would help. Right now we get the 
tables: connection.describeGlobal().getSobjects()
columns : connection.describeSObject(table.getName())

**Comment by paulpest** [comment]
I may not be explaining this properly. Please forgive me if I misstate something. I’m not an expert with Salesforce, or Python for that matter.

Oddly, the functions below don’t seem to return the description text. It returns everything else. Am I missing something?

To get the entity description, I used the following query through calling the tooling API using Python:
"Select QualifiedAPIName, Description from EntityDefinition where QualifiedAPIName > '" + max_entity + "' order by QualifiedAPIName LIMIT 2000"

To get the column descriptions, I used the following query, again through the tooling api. I pull the attributes one Entity at a time, for convenience:
"select EntityDefinition.QualifiedApiName, QualifiedApiName, Description from FieldDefinition Where EntityDefinition.QualifiedApiName= 'EntityName’”




PaulPest|Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
***@***.***
Direct:205.980.8384
Toll Free:  800.377.1614   Ext.809
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​

**Comment by wise-coders** [comment]
Thank you for your reply!
I was able to query this:
Select QualifiedApiName from EntityDefinition

but
Select Description from EntityDefinition

would fail. Also looking on this page, the Description column is not available:

[1] https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_entitydefinition.htm

If you have support with Salesforce, please ask them how to get the Description.

Best regards,
 Dragos Pruteanu

[1] https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_entitydefinition.htm

**Comment by paulpest** [comment]
Dragos,
Thank you for the reply.

Why do you say EntityDefinition Description is not available using the tooling API? Here is the field definition from the link you provided.
Description
Type
string
Properties
Filter, Nillable, Sort
Description
The description of the entity. A meaningful description makes it easier to distinguish between custom objects when they are viewed in a list. This field is available in Tooling API version 37.0 and later.



However, when I look at the tooling API FieldDefinition, I do not see the Description column….yet I’m pulling it using the my Python code. Let me check on this to see if I can determine where the Field Description is coming from in the Python package (salesforce-api) I’m using.

Our installation of Salesforce shows API version 48. When I check this version of the documentation, I see the same thing as above – Description is found for Entity, Description is not found in the documentation for Field. And yet using the previous queries, I am able to get the descriptions for both.

I’ll send additional information later today.




PaulPest|Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
***@***.***
Direct:205.980.8384
Toll Free:  800.377.1614   Ext.809
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​

**Comment by paulpest** [comment]
On the FieldDefinition page, if you scroll down to the CustomMetadata section, you find the description. This means, the description does not appear to be available for the standard Salesforce fields (within the standard base entities), but is available for all custom fields (on base and custom entities).

I hope this makes sense. Please let me know if you have further questions and I’ll try to help.

Thanks


PaulPest|Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
***@***.***
Direct:205.980.8384
Toll Free:  800.377.1614   Ext.809
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​
From: Paul Pest ***@***.***>
Sent: Monday, October 4, 2021 7:18 AM
To: wise-coders/salesforce-jdbc-driver ***@***.***>; wise-coders/salesforce-jdbc-driver ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [wise-coders/salesforce-jdbc-driver] Can't pull the Entity and Field Descriptions (#7)

Dragos,
Thank you for the reply.

Why do you say EntityDefinition Description is not available using the tooling API? Here is the field definition from the link you provided.
Description
Type
string
Properties
Filter, Nillable, Sort
Description
The description of the entity. A meaningful description makes it easier to distinguish between custom objects when they are viewed in a list. This field is available in Tooling API version 37.0 and later.



However, when I look at the tooling API FieldDefinition, I do not see the Description column….yet I’m pulling it using the my Python code. Let me check on this to see if I can determine where the Field Description is coming from in the Python package (salesforce-api) I’m using.

Our installation of Salesforce shows API version 48. When I check this version of the documentation, I see the same thing as above – Description is found for Entity, Description is not found in the documentation for Field. And yet using the previous queries, I am able to get the descriptions for both.

I’ll send additional information later today.



***@***.***<http://www.rxbenefits.com/>
Paul​
Pest
|
Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
Email:
***@***.******@***.***>
Direct:
205.980.8384<tel:205.980.8384>
Toll Free:  800.377.1614
   Ext.
809<fax:809>
***@***.***<http://www.rxbenefits.com/>
***@***.***<https://www.linkedin.com/company/rxbenefits-inc->
***@***.******@***.***,-86.7381431,16z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x88893d4ffaac9485:0x31634e9ad56beda!2m2!1d-86.731097!2d33.437186>
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).<https://www.rxbenefits.com/response-to-novel-coronavirus-covid-19/>
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​

**Comment by paulpest** [comment]
The last statement about FieldDefinition aligns with my last run against our Salesforce environment. The Account table is a standard Salesforce object. For the standard columns, I don’t get the descriptions returned. But for all the custom columns (which have __c appended to the names), the descriptions are being returned. For all custom objects (tables with __c appended to the name), all fields will return descriptions if they exist within Salesforce.



PaulPest|Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
***@***.***
Direct:205.980.8384
Toll Free:  800.377.1614   Ext.809
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​
From: Paul Pest ***@***.***>
Sent: Monday, October 4, 2021 7:36 AM
To: wise-coders/salesforce-jdbc-driver ***@***.***>; wise-coders/salesforce-jdbc-driver ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [wise-coders/salesforce-jdbc-driver] Can't pull the Entity and Field Descriptions (#7)

On the FieldDefinition page, if you scroll down to the CustomMetadata section, you find the description. This means, the description does not appear to be available for the standard Salesforce fields (within the standard base entities), but is available for all custom fields (on base and custom entities).

I hope this makes sense. Please let me know if you have further questions and I’ll try to help.

Thanks

***@***.***<http://www.rxbenefits.com/>
Paul​
Pest
|
Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
Email:
***@***.******@***.***>
Direct:
205.980.8384<tel:205.980.8384>
Toll Free:  800.377.1614
   Ext.
809<fax:809>
***@***.***<http://www.rxbenefits.com/>
***@***.***<https://www.linkedin.com/company/rxbenefits-inc->
***@***.******@***.***,-86.7381431,16z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x88893d4ffaac9485:0x31634e9ad56beda!2m2!1d-86.731097!2d33.437186>
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).<https://www.rxbenefits.com/response-to-novel-coronavirus-covid-19/>
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​
From: Paul Pest ***@***.******@***.***>>
Sent: Monday, October 4, 2021 7:18 AM
To: wise-coders/salesforce-jdbc-driver ***@***.******@***.***>>; wise-coders/salesforce-jdbc-driver ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [wise-coders/salesforce-jdbc-driver] Can't pull the Entity and Field Descriptions (#7)

Dragos,
Thank you for the reply.

Why do you say EntityDefinition Description is not available using the tooling API? Here is the field definition from the link you provided.
Description
Type
string
Properties
Filter, Nillable, Sort
Description
The description of the entity. A meaningful description makes it easier to distinguish between custom objects when they are viewed in a list. This field is available in Tooling API version 37.0 and later.



However, when I look at the tooling API FieldDefinition, I do not see the Description column….yet I’m pulling it using the my Python code. Let me check on this to see if I can determine where the Field Description is coming from in the Python package (salesforce-api) I’m using.

Our installation of Salesforce shows API version 48. When I check this version of the documentation, I see the same thing as above – Description is found for Entity, Description is not found in the documentation for Field. And yet using the previous queries, I am able to get the descriptions for both.

I’ll send additional information later today.



***@***.***<http://www.rxbenefits.com/>
Paul​
Pest
|
Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
Email:
***@***.******@***.***>
Direct:
205.980.8384<tel:205.980.8384>
Toll Free:  800.377.1614
   Ext.
809<fax:809>
***@***.***<http://www.rxbenefits.com/>
***@***.***<https://www.linkedin.com/company/rxbenefits-inc->
***@***.******@***.***,-86.7381431,16z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x88893d4ffaac9485:0x31634e9ad56beda!2m2!1d-86.731097!2d33.437186>
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).<https://www.rxbenefits.com/response-to-novel-coronavirus-covid-19/>
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​

**Comment by dprutean** [comment]
Thank you for your research. I am a bit lost with these entities. 
I can successfully execute this query from the DbSchema SQL Editor:
select QualifiedApiName, Description from FieldDefinition
But with an empty result.

This works: 
Select QualifiedApiName from EntityDefinition order by QualifiedApiName
and this fails, with unknown field:
Select Description from EntityDefinition order by QualifiedApiName

Next, I tried creating an object called DbSchema in the Web API:
![image](https://user-images.githubusercontent.com/4970910/135978723-40df0471-4873-46b5-bf5e-2dc45bd20607.png)

I don't get it in DbSchema, neither in the queries above. 
Do you have time for a web meeting? Please contact us per email and we can check together.

**Comment by paulpest** [comment]
The empty result set maybe correct. If your test instance doesn’t have the descriptions entered into Salesforce, then none will be returned. We have our Salesforce team entering the descriptions.

However, for some (if not most) of the standard base objects, Salesforce will not allow the description. For these, Salesforce has the descriptions published in their online documentation.

As additional information, while developing my Python code to pull the Entity and Field descriptions from Salesforce, the first package I tried was simple-salesforce. It appears to be the most popular Salesforce package for use with Python code. But it did not work for these tooling api calls. When I switched to the salesforce-api package, it works correctly for the tooling api calls. Both of these packages are published on pypi.org (the Python Package Index).

I’m in the Central Time zone. We can try to work out a call if you’d like. Thursday or Friday is the earliest I could meet.



PaulPest|Data Architect
RxBenefits, Inc.
3700 Colonnade Parkway, Suite 600, ​Birmingham, AL 35243
***@***.***
Direct:205.980.8384
Toll Free:  800.377.1614   Ext.809
Click here to learn more about RxBenefits' response to coronavirus (COVID-19).
Confidentiality Notice:  This message, including any attachments, is for the sole use of the intended recipients(s) and may contain confidential and privileged information, including confidential health information that is protected by the Health Insurance Portability and Accountability Act of 1996 and related regulations and other federal and state law. This message is not intended to be legal, medical, or financial advice. Please consult your own professionals for such advice. If you are not the intended recipient: (1) be advised that any use, disclosure, distribution, forwarding, printing, or copying of this message without sender’s written permission is strictly prohibited and may be unlawful; and (2) please contact the sender by reply e-mail and destroy all copies of the original message.
​
​
